name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Copy files via scp
        run: scp -r * ubuntu@5.75.184.186:/home/ubuntu/nostr/relayer

      - name: Run Docker Compose
        run: |
          ssh ubuntu@5.75.184.186 << 'EOF'
          cd /home/ubuntu/nostr/relayer
          docker-compose pull
          docker-compose up -d
          EOF
